int = input("Enter the year: ")
String1 = input("Enter the genre: ")
String2 = input("Enter the album: ")
String3 = input("Enter the song title: ")
String4 = input("Enter the artist: ")

print("--------------------------")
print("SONG DETAILS")
print("--------------------------")

print("Year Released: " , int)
print("Genre: ", String1)
print("Album: ", String2)
print("Title: ","\"" + String3 +"\"")
print("Artist: ", String4)