num1 = input("Enter the year: ")
name1 = input("Enter the genre: ")
name2 = input("Enter the album: ")
name3 = input("Enter the song title: ")
name4 = input("Enter the artist: ")

print("--------------------------")
print("SONG DETAILS")
print("--------------------------")

print("Year Released: " , num1)
print("Genre: ", name1)
print("Album: ", name2)
print("Title: ","\"" + name3 +"\"")
print("Artist: ", name4)